### PR TITLE
Snippet support

### PR DESCRIPTION
**Pull request by JoeyGrajciar**
Reopen of #82

### CODE REVIEW

**Comment by JoeyGrajciar** [comment]
@danymat Wondering if it makes sense to continue with this PR as friendly snippets have `norg` snippets present https://github.com/nvim-neorg/neorg/pull/82#issuecomment-985985916
Other issue is that `core.norg.completion` module interferes with snippets if trigger starts with `@`.

**Comment by mrossinek** [comment]
Okay, just for to understand, is the purpose of this PR to add snippets for common norg format structures?

I'm not sure what the common approach is here. Since snippet engines can differ in their syntax, it seems like quite some overhead to supply snippets for norg for possibly quite many snippet engines. Is that common practice or would rather snippet engines supply those in their source? (I'm not big on snippets so I honestly do not know :sweat_smile:)

**Comment by danymat** [comment]
> I'm not sure what the common approach is here. Since snippet engines can differ in their syntax, it seems like quite some overhead to supply snippets for norg for possibly quite many snippet engines. Is that common practice or would rather snippet engines supply those in their source? (I'm not big on snippets so I honestly do not know 😅)

I think that's the good idea, it is like the implementation of completion sources

**Comment by danymat** [comment]
> @danymat Wondering if it makes sense to continue with this PR as friendly snippets have norg snippets present #82 (comment)
Other issue is that core.norg.completion module interferes with snippets if trigger starts with @.

I think that's a good idea to add support for more snippets engine. I personally use luasnip and I don't know if we can supply norg snippets directly within luasnip repo

**Comment by danymat** [comment]
I don't think we can merge this until we fix the `@` issue

**Comment by vhyrro** [comment]
Hey! Unfortunately we'll be closing this PR. We don't see much value in providing snippets ourselves - this is something that snippet collections like friendly-snippets should do, that way not everything is centralized in Neorg itself.

Hope you understand!

**Comment by molleweide** [comment]
I published 'LuaSnip-snippets.nvim' a couple days ago where I'll try to add neorg snippets writtwn in lua.

**Pull request closed without merging**
