### PR TITLE
New Syntax Support

### PR DESCRIPTION
**Pull request by vhyrro**
My favourite part is when I get to say "it's stabilizing time" and stabilize all over Neorg.

# The Stabilization Phase begins!

Given that the base syntax is almost guaranteed to remain the same at this point onwards I believe it's the perfect time to start rewriting the major parts of Neorg to support the fresh new shiny stuff. A syntax converter would be nice as well.

# GTD might die, oops

GTD is so large that for the purposes of the rewrite it will be fully dropped and rewritten from scratch in a *follow up* PR after this one. Hey, I did tell you to not start using it professionally while it's in beta! smh

The GTD rewrite will be a more efficient, more performant and more integrated workflow. Also since I'll be the one working on it from the ground up I'll have a deeper understanding of the internals and will assist in the creation of some slick UIs. I'll also be able to help people troubleshoot the module now instead of helplessly pinging @danymat every time lol

### CODE REVIEW

**Comment by vhyrro** [comment]
We're close to completion by the way. Just the markdown exporter and the syntax converter :flushed:

**Comment by vhyrro** [comment]
Uh, maybe I shouldn't have said "just" the syntax converter. That thing is giving me so many headaches right now. I'm half contemplating on just pushing this as is and telling everyone "get good lol" but that's not the right move to make. Expect this PR to lay around here for a week or two while I try to fix up the syntax upgrade tool :)

**Comment by vhyrro** [comment]
Update: the upgrader works :flushed: :flushed: 

I'm just extensively testing it now to make sure your files don't randomly disappear after running it. Here's the plan of action:
1. Release the upgrade tool to the public, bump the Neorg version. Give everyone time to test the upgrade tool, to find bugs and problems with compatibility across platforms etc.
2. After we know for sure that the upgrade tool is good enough we merge this PR.
3. Update the upgrader to use the old parser (this is a note for future me more than anything, ignore this bit lol)

I'm so excited!! The GTD rewrite is going to be such a banger.

**Comment by Anrock** [comment]
Got an error when upgrading files, couple of them were corrupted. Should I create separate issue or reporting here is fine?
I'll try to get a minimal repro or provide an example later since the files have some sensitive data inside.
```
Error executing vim.schedule lua callback: ...ua/neorg/modules/core/integrations/treesitter/module.lua:291: Index out of bounds
stack traceback:
        [C]: in function 'nvim_buf_get_text'
        ...ua/neorg/modules/core/integrations/treesitter/module.lua:291: in function 'get_node_text'
        ...qs/start/neorg/lua/neorg/modules/core/upgrade/module.lua:140: in function <...qs/start/neorg/lua/neorg/modules/core/upgrade/module.lua:138>
        ...qs/start/neorg/lua/neorg/modules/core/upgrade/module.lua:67: in function 'callback'
        ...ua/neorg/modules/core/integrations/treesitter/module.lua:269: in function 'descend'
        ...ua/neorg/modules/core/integrations/treesitter/module.lua:271: in function 'descend'
        ...ua/neorg/modules/core/integrations/treesitter/module.lua:276: in function 'tree_map_rec'
        ...qs/start/neorg/lua/neorg/modules/core/upgrade/module.lua:55: in function 'upgrade'
        ...qs/start/neorg/lua/neorg/modules/core/upgrade/module.lua:283: in function <...qs/start/neorg/lua/neorg/modules/core/upgrade/module.lua:269>
```

**Comment by Anrock** [comment]
@bangedorrunt I believe. I ran PaqUpgrade, restarted neovim and saw news item about upgrade tool. Tried using it and boom.

Anyways, here's the minimal repro I've managed to devise. Last empty line is important too.
```
- [?] С
п

```

**Comment by Anrock** [comment]
Just to be clear: I'm on 579945d on main branch right now.

**Comment by danymat** [comment]
> I'm so excited!! The GTD rewrite is going to be such a banger.

Just adding my 2 cents here to cheer on the progress and say that I'm excited to take on GTD rewrite !

**Comment by vhyrro** [comment]
I sense a merge in the air...

**Comment by vhyrro** [comment]
1.0 BABY!

For reference:
- Reddit post and videos arriving in the span of 2/3 days
- I will be away for the next day or two but I'll be back to aggresively fix bugs
- We have migrated to true semver!

**Pull request merged**
