### PR TITLE
Revamp Internal Documentation

### PR DESCRIPTION
**Pull request by vhyrro**
More prep for 0.1 incoming - documentation is important! Not only in the wiki, but in the codebase too. Over the next few days (weeks?) I'll be working on making the documentation easy to understand and the codebase easy to follow. Later I'll draw my attention to the wiki so newcomers can have an easy time getting used to Neorg :)

### CODE REVIEW

**Comment by max397574** [comment]
remove custom parser installation from readme

**Comment by vhyrro** [comment]
Alright, I think this is good enough for the time being! The documentation is decently rich for how I want it to be and the automatic documentation generator has been buffed and optimized significantly. I'll continue work on this in a separate PR later down the line - one can only write documentation for so long before you feel like falling asleep :p

**Comment by roland-rollo** [comment]
@vhyrro I have question:
You deleted this from readme:
``lua
local parser_configs = require('nvim-treesitter.parsers').get_parser_configs()
-- These two are optional and provide syntax highlighting
-- for Neorg tables and the @document.meta tag
parser_configs.norg_meta = {
    install_info = {
        url = "https://github.com/nvim-neorg/tree-sitter-norg-meta",
        files = { "src/parser.c" },
        branch = "main"
    },
}
parser_configs.norg_table = {
    install_info = {
        url = "https://github.com/nvim-neorg/tree-sitter-norg-table",
        files = { "src/parser.c" },
        branch = "main"
    },
}
```

So I too deleted them from my `init.lua`, but then it give me:
```
Error detected while processing /home/roland/.config/nvim/init.lua:
E5113: Error while calling lua chunk: ...er/start/nvim-treesitter/lua/nvim-treesitter/install.lua:373: Parser not available for language
norg_meta
stack traceback:
        [C]: in function 'get_parser_install_info'
        ...er/start/nvim-treesitter/lua/nvim-treesitter/install.lua:373: in function 'install_lang'
        ...er/start/nvim-treesitter/lua/nvim-treesitter/install.lua:422: in function 'ensure_installed'
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:385: in function 'setup'
        /home/roland/.config/nvim/init.lua:213: in main chunk
```

My config
https://gist.github.com/roland-rollo/2ba9a5718dbfacc49bee6aad4f593c8f

**Comment by vhyrro** [comment]
@roland-rollo Hey man! Turns out the README is inaccurate, I'll update it in a bit. Basically the problem is the following:
- `norg_meta` does not exist natively in `nvim-treesitter`, that's why you get errors about it. 
- Only whenever you launch Neorg (`:NeorgStart` or by opening a `.norg` file) Neorg tells treesitter "hey, there's this parser called `norg_meta` you should know about" - treesitter only knows that `norg_meta` exists once you've entered a neorg file

To solve the problem:
- Remove `norg_meta` from `ensure_installed`
- Enter a `.norg` file and run `:Neorg sync-parsers` to install the meta parser instead

We could solve this problem by merging `norg_meta` into `nvim-treesitter`, but I don't know whether the TS guys will want a complementary parser in their main repos. I guess I could try. Hope that helps!

**Pull request merged**
