### PR TITLE
add shortcut to traverse link

### PR DESCRIPTION
**Pull request by shawaman**
added shortcut for link-traverse mode and updated syntax.

### CODE REVIEW

**Comment by shawaman** [comment]
@vhyrro Should I remove the link-traversal mode. Because Tab and Shift Tab is more natural to traverse through link and was used in vimwiki.

**Comment by max397574** [comment]
I'm quite sure that in the meantime there already was a mapping for the mode added
and imo we should keep it like this instead of mapping tab

**Comment by shawaman** [comment]
@max397574 
Previously added shortcut was for entering a separate mode and then traverse through link and you have to switch back to follow a link, which is to many steps.

Tabs can be used without entering any mode just like you follow a link using enter. This way is very simple and flows well with linking notes. Using Backspace to navigate backwards will also allow seamless notes reading like a wiki.

I Suggest to keep this simple way and remove the separate mode just to traverse a link and switch back to follow the link.

**Comment by max397574** [comment]
I disagree
I'm against mapping tab because it's such common key
just use the builtin <c-o> to jump back

What imo could be considered though is allowing to follow links in every mode
anyway this should be discussed in a discussion or an issue and not this pr which can be closed

**Pull request closed without merging**
