### PR TITLE
refactor(luacheck): workaround lua type check

### PR DESCRIPTION
**Pull request by pysan3**
- TODO: This should be dealt with later and eliminate the TODOs <2023-11-15, pysan3 pysan3@gmail.com>

### CODE REVIEW

**Comment by pysan3** [comment]
Alright we are good to go @vhyrro 

Dang it, there's a lot of places to fix.

And on top of that, this is not all of them since we have a lot of places where the type is simply `any` where the langserver lost track of the type.

Type errors for `any` are not raised now, but once we start resolving these, there will be more diagnostic errors.

**Comment by max397574** [comment]
I think the standard todo comment would be `TODO(pysan3): ...` without the `<pysan3>` at the end

**Comment by pysan3** [comment]
Hmm, that's interesting. My snippet does this and I blindly accepted it. 

I'll search where it is defined.

**Comment by pysan3** [comment]
https://github.com/L3MON4D3/LuaSnip/wiki/Cool-Snippets#todo-comments-snippets

BTW how'd you also add the date?

```lua
-- TODO: foo bar <2023-11-15, pysan3>
```

**Comment by max397574** [comment]
why would you do that?
that's just rly ugly and no need for it to be there

**Comment by pysan3** [comment]
Besides, your way of doing things will not be detected by https://github.com/folke/todo-comments.nvim.

Where can I get info or specs about that standard?

**Comment by max397574** [comment]
you could also just write no person at all
because in the end you're not the only person that can resolve the todos

**Comment by vhyrro** [comment]
> Besides, your way of writing the todo will not be detected by [folke/todo-comments.nvim](https://github.com/folke/todo-comments.nvim).
> 
> Where can I get info or specs about that standard you proposed?

That's odd hah. The treesitter comment parser will parse the `TODO(vhyrro)` comments in a different colour so I believe that's why everyone rolled with it.

This looks good to me! Doesn't matter what syntax it's using as long as it's informative and gets its point across. We'll be removing these anyway :)

**Pull request merged**
