### PR TITLE
refactor(export): return table instead values

### PR DESCRIPTION
**Pull request by danilshvalov**
I think using tables instead of a list of values will improve extensibility

### CODE REVIEW

**Comment by vhyrro** [comment]
This is a good idea for sure. You missed some parts of code (mainly at the top of the file), so I'll quickly fix those up if that's okay :p

**Comment by vhyrro** [comment]
I believe this should be everything. There are some conflicts now so I'll try dealing with them before we merge :)

**Comment by vhyrro** [comment]
Not a fan of the commit message autogenerate by github, but i'll squash w/ merge anyway so nobody shall see :p

Could you try this PR out one last time? See if there are any bugs/any weird behaviours. I couldn't find any so if you can't find any as well then it's merge time!

**Comment by danilshvalov** [comment]
Works well for me

**Comment by vhyrro** [comment]
Awesome, merged!

**Pull request merged**
