### PR TITLE
Various regex code block highlighting improvements

### PR DESCRIPTION
**Pull request by katawful**
Felt displeased with my implementation of regex code blocks, this PR addresses the majority of them

Issues:

- [ ] hi link groups clear when Neorg updates the code block syntax groups - NeoVim issue #315 
- [x] general performance issues, scheduling is perhaps wrong way to go about this
- [x] syntax settings from code blocks leak out #365 
- [x] regex languages aren't available for completion like treesitter languages
- [x] syntax files can "double" which leads to syntax markers to escape - ToC issue?
- [x] create new module for regex code block stuff

### CODE REVIEW

**Comment by katawful** [comment]
Performance fixes are almost done, but ultimately even a single well made syntax file will increase CPU time on the main thread by about double when a redraw call is made in my testing. It is a bit better for redraws, and significantly more reliable and less bloated for neorg events however. I have 1 more major performance fix I want to introduce and then it's cleanup time for the most part. This PR might hit 0.1 window but no guarantee

**Comment by katawful** [comment]
Performance fixes are done

**Comment by katawful** [comment]
I can't seem to replicate my issues with other syntax files that do the same thing, so my code is probably ok? Seems to be a bug in how Vim in general can accept some ways to do things, so its a bug in my own syntax files. Not going to mark that issue done until its 100% reliable however

**Comment by katawful** [comment]
Leaking issue seems mostly fixed now. Going to do some more writing in Neorg just to confirm the functionality, but I think I have done everything I possibly can to stop it from ever happening while also allowing all broken language features to still work

**Comment by katawful** [comment]
Everything in my list is done, think its read for review

**Comment by danymat** [comment]
I want to test this, but I don't know what I'm looking out. Can you pinpoint some basic steps for testing, and what I should be aware of ?

**Comment by katawful** [comment]
Ideally there shouldn't be anything out of the ordinary, I've tested this a lot. My suggestion is to get some various regular syntax languages you know of, preferably ones that might contain more features like syntax folding and the like, and see how they work while plainly using Neorg. Like using Telescope or FZF to switch files, using GTD regularly, etc... I haven't done much of that recently

**Comment by katawful** [comment]
Hmm, regular Vim jumps doesn't cause the doubling issue but Neorg hop jumps do (like ToC)

**Comment by katawful** [comment]
Using fzf-lua with full buffer previews seems broken. Carries the preview buffers over. I presume that telescope does the same. Will have to check to fix this

**Comment by katawful** [comment]
Ok, I think I've finally fixed it all for real this time. Barring the conflicts in the concealer module which needs to be fixed, I haven't found any immediate issues

**Comment by katawful** [comment]
Vim regex is not good enough to do everything we need for Neorg, and with no sign of that changing, some use will have to be broken

**Comment by vhyrro** [comment]
:purple_heart:

**Pull request merged**
