### PR TITLE
feat: add new UI basics

### PR DESCRIPTION
**Pull request by vhyrro**
This PR is here in order to completely revamp the selection popup UI aspect of Neorg into something a lot more configurable.

This very super duper configurable UI will then be utilized in parts like GTD which will be incredibly important.
Rather than using static tables Neorg will now use the Neogit-style approach of incrementally defining parts of the selection popups and then building that popup in the end. We added a bit of a twist to it though thanks to the usage of extmarks and all round a bunch more extensibility (like configurability of the renderer and individual components like switches or text).

This is still very much a WIP but it's crucial in order to push forward the development of GTD (@danymat has pretty much finished the GTD base, we now need UIs in order to progress).

### CODE REVIEW

**Comment by vhyrro** [comment]
We're kind of stuck in an annoying predicament when it comes to the implementation. I'm considering scrapping it and starting afresh because there are just many things that don't add up properly when it comes to implementing it. I think the Neogit-OOP style isn't the best in this case if I wanna implement a generic solution for selection popups. I don't know how exactly to implement it differently though. I'd love to go for a more functional approach but idk what that'd look like.

**Comment by vhyrro** [comment]
Ok this is sort of a weird question but does anyone know how to handle key presses in a "better" way? `vim.api.nvim_buf_set_keymap` only takes in a string and that's fairly tragic considering a lot of the code relies on local functions. Is there a way to get the user input in a non-blocking manner and also a way to invoke a local lua function from it?

**Comment by danymat** [comment]
> Is there a way to get the user input in a non-blocking manner and also a way to invoke a local lua function from it?

I was thinking about using `nvim_buf_attach` in order to inspect the actual key presses. Wdyt?

**Comment by vhyrro** [comment]
As Dany and I discussed on discord it turns out that that wasn't the way to go. In fact there was no way to go: even the not-well-known `vim.on_key` function didn't help us much when it came to parsing inputs in the selection popup. I ended up simply using `vim.api.nvim_buf_set_keymap` in the end. Good news though! The new implementation is very flexible and absolutely awesome! It'll definitely be extensible enough for use in almost any scenario and could potentially be extracted for use in other plugins.

**Comment by vhyrro** [comment]
I'll be extending it more and more until I'm satisfied. Might be done in a day or two.

**Comment by danymat** [comment]
Just finished moving the gtd selection popup to this new api. 
It works very well and I did some adjustments and bug fixes.

Capture d’écran 2021-09-20 à 09 04 28

I'm looking forward to such features:
- Prompt integrated with the selection popup
- Switch flag

**Comment by danymat** [comment]
I created a prompt integrated with the selection popup, that is very configurable. I head that @vhyrro will refactor it a little bit, but the idea is that we reuse the same buffer in order to add a prompt line somewhere, like this code:

```lua
selection
    :title("Test")
    :blank()
    :prompt("Input", callback)
```

This is the created prompt for creating a task:

Capture d’écran 2021-09-20 à 14 37 18

**Comment by TimUntersberger** [comment]
Are there any plans on moving this into a seperate plugin or into plenary so other plugins can reuse this functionality?

I have only seen a shallow overview of the PR, but so far I really like the direction your selection popups are going in.

**Comment by vhyrro** [comment]
@TimUntersberger Yeah we'd love to extract this once we're done and reimplement it for a different codebase like plenary for example, shouldn't be difficult thankfully because there's not much reliance on Neorg-specific code. It'll close #98 if all goes well :)

**Comment by danymat** [comment]
Okay the little mess I did above was me trying to decouple the multifile module, because it was doing a lot of problems.
I will wait for merging unstable into this PR until it is fixed

**Comment by danymat** [comment]
The new UI is quite stable, so I'm merging this PR into `gtd_base` in order to avoid duplicates and dead branches.
We will open new PR's for upcoming changes on the UI.

**Pull request merged**
