### PR TITLE
feat: allow arguments for `:Neorg generate-workspace-summary`

### PR DESCRIPTION
**Pull request by Dynge**
Closes: #1086 

# Changes
This pull request changes the generate-workspace-summary in two ways:

1. The `Neorg generate-workspace-summary` command now takes optional arguments.
2. Added a public function `generate_workspace_summary` such that it can be called through lua directly if needed.

# Needs feedback
The way it is implemented in this pull request accomplishes the goal by separating the arguments by space for separate categories, meaning you cannot target a category containing spaces with the neorgcmd.

I am not sure what is the better implementation - this or one where the Neorgcmd merges all inputs into a single category.

### CODE REVIEW

**Comment by vhyrro** [comment]
This looks good to me! Could you also add a small explanation to the comment at the top of the file explaining what the arguments to the `:Neorg generate-workspace-summary` command do? Would be appreciated :)

**Comment by Dynge** [comment]
Sounds great.

I've added a line or two explaining how to use arguments for the command.
Let me know if it is satisfactory :)

**Comment by Dynge** [comment]
Not sure I understand why the build failed.

I don't see any logs related to the summary module. :/ 

Do I need to revert my merge commit from `neorg/main`?

**Comment by pysan3** [comment]
Nope you are alright. 

It's this https://github.com/nvim-neorg/neorg/pull/1161. 

I and @vhyrro will look into fixing the type errors but it will take time. Until then, you can ignore the lua_ls type check action. (If others are failing, then that's a problem tho)

**Comment by vhyrro** [comment]
> Sounds great.
> 
> I've added a line or two explaining how to use arguments for the command. Let me know if it is satisfactory :)

Perfect, thank you for the PR! :)

**Pull request merged**
