### PR TITLE
feat(snippets): support for Neorg snippets

### PR DESCRIPTION
**Pull request by JoeyGrajciar**
Basic snippet support for now `code` and `image` blocks.

- [ ] vsnip
- [x] luasnip
- [ ] moar snippets
- [ ] sane triggers for snippets

Showcase:
luasnip_neorg

### CODE REVIEW

**Comment by JoeyGrajciar** [comment]
Users of `vim-vsnip` could you check if my assumptions are correct? 😄 
In neorg configuration use
```
["core.norg.snippet"] = {
   config = {
       engine = "vsnip"
   }
}
```

**Comment by danymat** [comment]
Hello, what's the state of this PR ?

**Comment by JoeyGrajciar** [comment]
I would say that `vsnip` could be checked although I did not test it.
It should be rebased on top of main and probably fixed (wasn't there some change in modules?).
Afterwards snippets could be added. Lost track of new things so help would be appreciated :)

**Comment by ashincoder** [comment]
I have already added norg snippets in https://github.com/rafamadriz/friendly-snippets/commit/154e9ab585908844ae94d5623beeb2ac9ae6beee.

**Comment by danymat** [comment]
@JoeyGrajciar  We deleted unstable branch, in favor of having only `main` branch. Can you reopen the issue by pointing the PR to main `instead` ?

**Pull request closed without merging**
