### PR TITLE
add cheatsheet

### PR DESCRIPTION
**Pull request by max397574**
closes https://github.com/nvim-neorg/neorg/issues/419

### CODE REVIEW

**Comment by max397574** [comment]
for now I just copied that example file
We should change that though

**Comment by max397574** [comment]
@premell is this what you though about?

**Comment by max397574** [comment]
@vhyrro 
the tests that fail have nothing to do with this pr right?

**Comment by vhyrro** [comment]
Tests failing are "normal" :p

If i get some time i'll populate the contents of the cheatsheet to have something more enticing than just a copy of the example file

**Comment by mrossinek** [comment]
I don't think it's a good idea to effectively duplicate the examples file in this format. We already have too many files which need to be kept consistent and with the formal syntax specification moving to the TS repo, the documentation over here will also need to be overhauled. Just my two cents..

**Comment by max397574** [comment]
Yes
for now I just added the example file (added links) because it was mainly about the floating window things etc
Eventually we should write a compact cheatsheet

**Comment by max397574** [comment]
@vhyrro ?

**Comment by vhyrro** [comment]
I've just spent a bit of time compiling a larger cheatsheet that is just a simple helpfile for the time being (`:h neorg-cheatsheet`). In my opinion we should close this PR and we can work from the ground up on a solution that revolves around the new cheatsheet file with features like "show automatically when it's the user's first time installing neorg", a tutorial mode (if you've seen conjure's tutorial then i'd love something along those lines) and so on.

This PR not being merged became kind of a meme at this point but it can't just be here forever :smile:

**Pull request closed without merging**
