### PR TITLE
feat(concealer): conceal numeric footnote title to superscript 

### PR DESCRIPTION
**Pull request by champignoom**
Resolves https://github.com/nvim-neorg/neorg/issues/1189.

### CODE REVIEW

**Comment by max397574** [comment]
just wondering
why are some autocommands commented out?
if they should be removed remove them
if this is a wip mark it as draft

**Comment by champignoom** [comment]
See https://github.com/nvim-neorg/neorg/pull/1186, on which this PR happens to be based.

I'll rebase it to main if that solves the problem.

**Comment by max397574** [comment]
much nicer diff like this

**Comment by vhyrro** [comment]
This is beyond an awesome idea. The concealer is easily the coolest part of the Neorg TUI experience right now :rocket:

**Pull request merged**
