### PR TITLE
Pandoc module

### PR DESCRIPTION
**Pull request by danymat**
This is the PR responsible for creating pandoc conversions from neorg to other formats (see https://github.com/jgm/pandoc/issues/7495)

### CODE REVIEW

**Comment by Simre1** [comment]
I have set up a repo here: https://github.com/Simre1/neorg-haskell-parser

Most features are still missing. I hope I will be able to cover the whole specification in a reasonable amount of time.

**Comment by MordechaiHadad** [comment]
> 
> 
> I have set up a repo here: https://github.com/Simre1/neorg-haskell-parser
> 
> Most features are still missing. I hope I will be able to cover the whole specification in a reasonable amount of time.

You should join the neorg discord server

**Comment by vhyrro** [comment]
> I have set up a repo here: https://github.com/Simre1/neorg-haskell-parser
> 
> Most features are still missing. I hope I will be able to cover the whole specification in a reasonable amount of time.

If ya ever need help with anything regarding the spec (if you find an inconsistency or something's unclear) then give me a shout! I wish I was as good at haskell so I could contribute and help out but I'm not I'm afraid :/

**Comment by danymat** [comment]
Closing this PR as @Simre1 is on a good streak of creating the pandoc parser.

**Pull request closed without merging**
