### PR TITLE
clean up helpfiles

### PR DESCRIPTION
**Pull request by max397574**

### CODE REVIEW

**Comment by mrossinek** [comment]
Are you cleaning up all help files or is this meant for only this one?

**Comment by max397574** [comment]
Originally I planned only this but there are others who still use the old links so I'll do those as well

**Comment by mrossinek** [comment]
> Originally I planned only this but there are others who still use the old links so I'll do those as well

Cool! While you're at it, could you please also check the contents of the `tags` file? I remember a discussion somewhere someone pointing out that `neorg-foreplay` doesn't work. The target no longer exists but it is still present in the `tags` file.

**Comment by max397574** [comment]
foreplay is no longer a tag

**Comment by danymat** [comment]
Merged, thanks !

**Pull request merged**
