### PR TITLE
refactor(promo): rewrite module to fix several bugs

### PR DESCRIPTION
**Pull request by champignoom**
Fixes https://github.com/nvim-neorg/neorg/issues/795 and https://github.com/nvim-neorg/neorg/issues/803 and https://github.com/nvim-neorg/neorg/issues/822

### CODE REVIEW

**Comment by vhyrro** [comment]
Very nice, thanks a lot for taking the time to do this! A future TODO would be to add descriptive error messages for when a possible assertion fails, so the user doesn't just get a traceback. Would you like to do that in this PR, or should we just make this a TODO for another day and merge now? I'm happy with either option tbh :)

**Comment by champignoom** [comment]
Sure but the assertions are meant to help the developers rather than the users, so the error message might be only as readable as "internal error encountered, please create an issue" plus a table of all involved values.

**Comment by pysan3** [comment]
FYI, this push is failing the luacheck test over on the main branch...
https://github.com/nvim-neorg/neorg/actions/runs/4832513182/jobs/8611381927

image

**Comment by vhyrro** [comment]
Yep I'm aware, I'm fixing them up as we speak :)

**Pull request merged**
